Handle arbitrary interface names in wifi command

diff --git a/saltstack/salt/network/wifi b/saltstack/salt/network/wifi
--- a/saltstack/salt/network/wifi
+++ b/saltstack/salt/network/wifi
@@ -1,34 +1,38 @@
 #! /bin/bash
 
-WIFI=wlp1s0
+CONF=wlp1s0
+
+if test -z "$WIFI"; then
+    WIFI=wlp1s0
+fi
 
 offline 2> /dev/null
 
 ip link set "$WIFI" up && \
     if [ $# -eq 0 ]; then
-	wpa_supplicant -B -m '' -i "$WIFI" -c "/etc/wpa_supplicant/$WIFI.conf"
+        wpa_supplicant -B -m '' -i "$WIFI" -c "/etc/wpa_supplicant/$CONF.conf"
     else
-	if ! grep -q '^ *ssid="'"$1"'"$' "/etc/wpa_supplicant/$WIFI.conf"; then
-	    echo "SSID $1 not found in /etc/wpa_supplicant/$WIFI.conf" >&2
-	    exit 1
-	fi
-	wpa_supplicant -B -m '' -i "$WIFI" -c <(awk '
-	    BEGIN {
-		keep = 0
-	    }
-	    /^ *ssid="'"$1"'"$/ {
-		print "network={"
-		keep = 1
-	    }
-	    {
-		if (keep) {
-		    print
-		}
-	    }
-	    /^}$/ {
-		keep = 0
-	    }
-	' "/etc/wpa_supplicant/$WIFI.conf")
+        if ! grep -q '^ *ssid="'"$1"'"$' "/etc/wpa_supplicant/$CONF.conf"; then
+            echo "SSID $1 not found in /etc/wpa_supplicant/$CONF.conf" >&2
+            exit 1
+        fi
+        wpa_supplicant -B -m '' -i "$WIFI" -c <(awk '
+            BEGIN {
+                keep = 0
+            }
+            /^ *ssid="'"$1"'"$/ {
+                print "network={"
+                keep = 1
+            }
+            {
+                if (keep) {
+                    print
+                }
+            }
+            /^}$/ {
+                keep = 0
+            }
+        ' "/etc/wpa_supplicant/$CONF.conf")
     fi && \
     dhcpcd "$WIFI" && \
     iw "$WIFI" link
