Add support for git worktrees
In the case of git worktrees, .git is a file, not a directory.

diff --git a/zsh/.zsh/vcs b/zsh/.zsh/vcs
--- a/zsh/.zsh/vcs
+++ b/zsh/.zsh/vcs
@@ -5,25 +5,25 @@ VCS=
 PREVIOUS_PWD=
 
 whichvcs() {
-	local base_dir
+    local base_dir
 
-	if [[ -d .svn ]]; then
-		echo svn
-	elif [[ -d CVS ]]; then
-		echo cvs
-	else
-		base_dir=.
-		while [[ ! -d $base_dir/.hg && ! -d $base_dir/.git&& ! -d $base_dir/.svn && $base_dir:A != / ]]; do
-			base_dir=$base_dir/..
-		done
-		if [[ -d $base_dir/.hg/ ]]; then
-		    echo hg
-		elif [[ -d $base_dir/.git/ ]]; then
-		    echo git
-		elif [[ -d $base_dir/.svn/ ]]; then
-		    echo svn
-		fi
-	fi
+    if [[ -d .svn ]]; then
+        echo svn
+    elif [[ -d CVS ]]; then
+        echo cvs
+    else
+        base_dir=.
+        while [[ ! -d $base_dir/.hg && ! ( -d $base_dir/.git || -f $base_dir/.git ) && ! -d $base_dir/.svn && $base_dir:A != / ]]; do
+            base_dir=$base_dir/..
+        done
+        if [[ -d $base_dir/.hg/ ]]; then
+            echo hg
+        elif [[ -d $base_dir/.git/ || -f $base_dir/.git ]]; then
+            echo git
+        elif [[ -d $base_dir/.svn/ ]]; then
+            echo svn
+        fi
+    fi
 }
 
 typeset -A VCS_REVISION
@@ -38,22 +38,22 @@ update_vcs_information() {
         VCS="[svn:$(svn info | sed -n '/R.vision \?:/ s/.* \(.*\)/\1/p')]"
     fi
     base_dir='.'
-    while [[ ! -d $base_dir/.hg && ! -d $base_dir/.git && ! -d $base_dir/.svn && $base_dir:A != / ]]; do
-	base_dir=$base_dir/..
+    while [[ ! -d $base_dir/.hg && ! ( -d $base_dir/.git || -f $base_dir/.git ) && ! -d $base_dir/.svn && $base_dir:A != / ]]; do
+        base_dir=$base_dir/..
     done
     if [[ -d $base_dir/.hg/ ]]; then
-	if [[ -f $base_dir/.hg/branch ]]; then
-	    VCS="${VCS}[hg:$(< $base_dir/.hg/branch):$(hg id -n)]"
-	else
-	    VCS="${VCS}[hg:default:$(hg id -n)]"
-	fi
-    elif [[ -d $base_dir/.git/ ]]; then
-	branch=$(git branch | command grep '^\*')
-	if git describe --always >& /dev/null; then
-	    VCS="${VCS}[git:$branch[3,-1]:$(git describe --always)]"
-	else
-	    VCS="${VCS}[git:uncommited]"
-	fi
+        if [[ -f $base_dir/.hg/branch ]]; then
+            VCS="${VCS}[hg:$(< $base_dir/.hg/branch):$(hg id -n)]"
+        else
+            VCS="${VCS}[hg:default:$(hg id -n)]"
+        fi
+    elif [[ -d $base_dir/.git/ || -f $base_dir/.git ]]; then
+        branch=$(git branch | command grep '^\*')
+        if git describe --always >& /dev/null; then
+            VCS="${VCS}[git:$branch[3,-1]:$(git describe --always)]"
+        else
+            VCS="${VCS}[git:uncommited]"
+        fi
     elif [[ -d $base_dir/.svn/ ]]; then
         VCS="[svn:$(svn info | sed -n '/R.vision \?:/ s/.* \(.*\)/\1/p')]"
     fi
@@ -65,8 +65,8 @@ update_vcs_information_if_needed() {
     # TODO idem si derniere commande = git checkout
     VCS=$VCS_REVISION[$PWD]
     if [[ -z $NO_VCS_INFO ]] && [[ -z $VCS ]] && [[ -z $PREVIOUS_PWD || $PREVIOUS_PWD != $PWD ]]; then
-	PREVIOUS_PWD=$PWD
-	update_vcs_information
+        PREVIOUS_PWD=$PWD
+        update_vcs_information
     fi
 }
 
@@ -78,7 +78,7 @@ vcsroot () {
 
     base_dir=.
     while [[ -d $base_dir/../.svn || -d $base_dir/../CVS || $base_dir:A == */$~vcsrootpattern/* ]] && [[ $base_dir:A != */$~vcsrootpattern ]]; do
-	base_dir=$base_dir/..
+        base_dir=$base_dir/..
     done
     echo "Running $cmd on $base_dir:A"
     $cmd $@ $base_dir
@@ -89,7 +89,7 @@ runinroot () {
 
     base_dir=.
     while [[ -d $base_dir/../.svn || -d $base_dir/../CVS || $base_dir:A == */$~vcsrootpattern/* ]] && [[ $base_dir:A != */$~vcsrootpattern ]]; do
-	base_dir=$base_dir/..
+        base_dir=$base_dir/..
     done
     if [[ $base_dir:A == */$~vcsrootpattern ]]; then
         runin $base_dir $@
@@ -102,8 +102,8 @@ co() {
     git clone $@  ||
     cvs -d $1 co $2 ||
     (
-	echo This is not a know repository >&2
-	return 1
+        echo This is not a know repository >&2
+        return 1
     )
 }
 
@@ -114,8 +114,8 @@ ch() {
 
 colorizeAdd() {
     while read line; do
-	line=$(echo $line | sed -e 's/^A[ 	].\+/\\e[1;32m&\\e[0m/')
-	echo $line
+        line=$(echo $line | sed -e 's/^A[ 	].\+/\\e[1;32m&\\e[0m/')
+        echo $line
     done
 }
 
@@ -124,17 +124,17 @@ add() {
 
     vcs=$(whichvcs)
     case $vcs in
-	svn)
-	    svn add $@ | colorizeAdd
-	;;
-	cvs)
-	    for path; do
-		find $path -exec cvs add {} | colorizeAdd \;
-	    done
-	;;
-	hg|git)
-	    $vcs add $@
-	;;
+        svn)
+            svn add $@ | colorizeAdd
+        ;;
+        cvs)
+            for path; do
+                find $path -exec cvs add {} | colorizeAdd \;
+            done
+        ;;
+        hg|git)
+            $vcs add $@
+        ;;
     esac
 }
 
@@ -143,12 +143,12 @@ unadd() {
 
     vcs=$(whichvcs)
     case $vcs in
-	svn)
-	    svn rm -R --keep-local $@ | colorizeAdd
-	;;
-	git)
-	    $vcs unadd $@
-	;;
+        svn)
+            svn rm -R --keep-local $@ | colorizeAdd
+        ;;
+        git)
+            $vcs unadd $@
+        ;;
     esac
 }
 
@@ -161,19 +161,19 @@ ci() {
     # same for df / rdf / dfl / rdfl / st / rst...
     vcs=$(whichvcs)
     case $vcs in
-	svn|cvs)
-	    $vcs ci $@
-	;;
-	hg)
-	    hg ci -v $@
-	;;
-	git)
-	    if ((#)); then
-		git commit -S $@
-	    else
-		git commit -Sa $@
-	    fi
-	;;
+        svn|cvs)
+            $vcs ci $@
+        ;;
+        hg)
+            hg ci -v $@
+        ;;
+        git)
+            if ((#)); then
+                git commit -S $@
+            else
+                git commit -Sa $@
+            fi
+        ;;
     esac
 
     update_vcs_information
@@ -212,22 +212,22 @@ push() {
 
     vcs=$(whichvcs)
     case $vcs in
-	hg|git)
-	    $vcs push $@
-	;;
+        hg|git)
+            $vcs push $@
+        ;;
     esac
 }
 
 colorizeStatus() {
     while read line; do
-	line=$(echo $line | sed -e '
+        line=$(echo $line | sed -e '
                 s/^A[ 	].\+/\\e[1;32m&\\e[0m/' -e '
                 s/^D[ 	].\+/\\e[1;31m&\\e[0m/' -e '
                 s/^[MU][ 	].\+/\\e[1;34m&\\e[0m/' -e '
                 s/^C[ 	].\+/\\e[1;91m&\\e[0m/' -e '
                 s/^[?G][ 	].\+/\\e[1;35m&\\e[0m/' -e '
                 s/35\(m?[ 	].\+\.\(log\|bak\|local\)\)/38;5;239\1/')
-	echo $line
+        echo $line
     done
 }
 
@@ -236,33 +236,33 @@ st() {
 
     vcs=$(whichvcs)
     case $vcs in
-	svn|cvs)
-	    if [[ $1 = '-f' ]]; then
-		shift
-		$vcs st $@ | grep -v '^\?' | colorizeStatus
-	    else
-		$vcs st $@ | colorizeStatus
-	    fi
-	;;
-	hg)
-	    hg st $@ .
-	;;
-	git)
-	    if [[ $1 = '-f' ]]; then
-		shift
-		if ((#)); then
-		    git st -uno $@
-		else
-		    git st -uno .
-		fi
-	    else
-		if ((#)); then
-		    git st $@
-		else
-		    git st .
-		fi
-	    fi
-	;;
+        svn|cvs)
+            if [[ $1 = '-f' ]]; then
+                shift
+                $vcs st $@ | grep -v '^\?' | colorizeStatus
+            else
+                $vcs st $@ | colorizeStatus
+            fi
+        ;;
+        hg)
+            hg st $@ .
+        ;;
+        git)
+            if [[ $1 = '-f' ]]; then
+                shift
+                if ((#)); then
+                    git st -uno $@
+                else
+                    git st -uno .
+                fi
+            else
+                if ((#)); then
+                    git st $@
+                else
+                    git st .
+                fi
+            fi
+        ;;
     esac
 }
 stf() {
@@ -277,7 +277,7 @@ stl() {
 stm() {
     local files
     for file in $(nocolor st -f | grep '^[^X] ' | cut -d ' ' -f 2); do
-	files+=($file)
+        files+=($file)
     done
     echo $files
 }
@@ -299,9 +299,9 @@ sls() {
 
     vcs=$(whichvcs)
     case $vcs in
-	svn)
-	    $vcs ls $(svn info --xml | xmlstarlet sel -T -t -c '//info/entry/url')/"$1"
-	;;
+        svn)
+            $vcs ls $(svn info --xml | xmlstarlet sel -T -t -c '//info/entry/url')/"$1"
+        ;;
     esac
 
     update_vcs_information
@@ -312,15 +312,15 @@ up() {
 
     vcs=$(whichvcs)
     case $vcs in
-	svn|cvs)
-	    $vcs up $@ | colorizeStatus
-	;;
-	hg)
-	    hg fetch $@
-	;;
-	git)
-	    git pull $@
-	;;
+        svn|cvs)
+            $vcs up $@ | colorizeStatus
+        ;;
+        hg)
+            hg fetch $@
+        ;;
+        git)
+            git pull $@
+        ;;
     esac
 
     update_vcs_information
@@ -337,30 +337,30 @@ dfcmd() {
 
     vcs=$(whichvcs)
     case $vcs in
-	svn)
-	    svn diff --diff-cmd=$cmd $@
-	;;
-	cvs)
-	    cvs diff $@
-	;;
-	hg)
-	    base_dir=.
-	    while [[ ! -d $base_dir/.hg ]]; do
-		base_dir=$base_dir/..
-	    done
-	    for file in $(hg st | sed -n '/^M/ s/^M //p'); do
-		echo
-		print '\e[1;33m***' $file '***\e[0m'
-		hg df $@ $base_dir/$file
-	    done
-	;;
-	git)
-	    if ((#)); then
-		git df --color $@
-	    else
-		git df --color .
-	    fi
-	;;
+        svn)
+            svn diff --diff-cmd=$cmd $@
+        ;;
+        cvs)
+            cvs diff $@
+        ;;
+        hg)
+            base_dir=.
+            while [[ ! -d $base_dir/.hg ]]; do
+                base_dir=$base_dir/..
+            done
+            for file in $(hg st | sed -n '/^M/ s/^M //p'); do
+                echo
+                print '\e[1;33m***' $file '***\e[0m'
+                hg df $@ $base_dir/$file
+            done
+        ;;
+        git)
+            if ((#)); then
+                git df --color $@
+            else
+                git df --color .
+            fi
+        ;;
     esac
 }
 df() {
@@ -448,11 +448,11 @@ dlf() {
     removed=$($cmd diff $@ | sed -n '/^-/p' | wc -l)
     difference=$((added-removed))
     if ((difference > 0)) then
-	echo "+$added\t-$removed\t(\e[32m+$difference\e[0m)"
+        echo "+$added\t-$removed\t(\e[32m+$difference\e[0m)"
     elif ((difference < 0)) then
-	echo "+$added\t-$removed\t(\e[31m$difference\e[0m)"
+        echo "+$added\t-$removed\t(\e[31m$difference\e[0m)"
     else
-	echo "+$added\t-$removed\t(0)"
+        echo "+$added\t-$removed\t(0)"
     fi
 }
 
@@ -463,8 +463,8 @@ dla() {
     shift
 
     for file in $($cmd st | sed -n '/^M/ s/^M //p'); do
-	printf "$file\t"
-	dlf $cmd $@ $file
+        printf "$file\t"
+        dlf $cmd $@ $file
     done
     echo ----------
     printf 'Total\t'
@@ -476,9 +476,9 @@ dl() {
 
     vcs=$(whichvcs)
     case $vcs in
-	*)
-	    dla $vcs $@
-	;;
+        *)
+            dla $vcs $@
+        ;;
     esac
 }
 
@@ -491,15 +491,15 @@ rv() {
 
     vcs=$(whichvcs)
     case $vcs in
-	cvs|hg)
-	    $vcs revert $@
-	;;
-	svn)
-	    svn revert -R $@
-	;;
-	git)
-	    git checkout $@
-	;;
+        cvs|hg)
+            $vcs revert $@
+        ;;
+        svn)
+            svn revert -R $@
+        ;;
+        git)
+            git checkout $@
+        ;;
     esac
 }
 
@@ -508,15 +508,15 @@ bo() {
 
     vcs=$(whichvcs)
     case $vcs in
-	hg)
-	    hg backout --merge $@
-	;;
-	svn)
-	    svn merge $@
-	;;
-	git)
-	    git revert $@
-	;;
+        hg)
+            hg backout --merge $@
+        ;;
+        svn)
+            svn merge $@
+        ;;
+        git)
+            git revert $@
+        ;;
     esac
 }
 
@@ -525,9 +525,9 @@ lg() {
 
     vcs=$(whichvcs)
     case $vcs in
-	*)
-	    $vcs log $@
-	;;
+        *)
+            $vcs log $@
+        ;;
     esac
 }
 rlg() {
@@ -538,15 +538,15 @@ lgv() {
 
     vcs=$(whichvcs)
     case $vcs in
-	cvs)
-	    $vcs log $@ | less
-	;;
-	git)
-	    git log -v --graph $@
-	;;
-	*)
-	    $vcs log -v $@ | less
-	;;
+        cvs)
+            $vcs log $@ | less
+        ;;
+        git)
+            git log -v --graph $@
+        ;;
+        *)
+            $vcs log -v $@ | less
+        ;;
     esac
 }
 rlgv() {
@@ -557,12 +557,12 @@ gl() {
 
     vcs=$(whichvcs)
     case $vcs in
-	hg)
-	    hg glog $@
-	;;
-	git)
-	    git log --graph $@
-	;;
+        hg)
+            hg glog $@
+        ;;
+        git)
+            git log --graph $@
+        ;;
     esac
 }
 lc() {
@@ -578,18 +578,18 @@ purge() {
     files=()
 
     for file in $(nocolor st | sed -n 's/^? \+\(.\+\)$/\1/p'); do
-	files+=($file)
+        files+=($file)
     done
 
     echo 'Will purge the following files:'
     for file in $files; do
-	echo "  $file"
+        echo "  $file"
     done
     echo 'Proceed?'
     read y
     if [[ $y != (y|Y) ]]; then
-	echo 'Operation aborted' >&2
-	return 1
+        echo 'Operation aborted' >&2
+        return 1
     fi
     rm -r $files
 }
@@ -617,13 +617,13 @@ ava() {
     revs=()
     IFS=,
     for r in $(av); do
-	if ((${#r} > 7)); then
-	    IFS=-
-	    a=($=r)
-	    revs+=($(seq -s '-' $a[1] $a[2]))
-	else
-	    revs+=($r)
-	fi
+        if ((${#r} > 7)); then
+            IFS=-
+            a=($=r)
+            revs+=($(seq -s '-' $a[1] $a[2]))
+        else
+            revs+=($r)
+        fi
     done
     echo $revs
 }
